import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./components/header";
import Container from "./components/container";
import SideBar from "./components/sidebar";
import useResponsive from "./hooks/use-responsive";
import ResponsiveMain from "./components/responsive-main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SD Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex">
          <SideBar />
          <main className="flex-1">
            <ResponsiveMain>
              <Header />
              {/* <HeaderMobile /> */}
              <Container>{children}</Container>
            </ResponsiveMain>
          </main>
        </div>
      </body>
    </html>
  );
}
