import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "../components/header";
import Container from "../components/container";
import SideBar from "../components/sidebar";
import Provider from "./StoreProvider";
import ResponsiveMain from "../components/responsive-main";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class">
          <Provider>
            <div className="flex">
              <SideBar />
              <main className="flex-1">
                <ResponsiveMain>
                  <Header />
                  <Container>{children}</Container>
                </ResponsiveMain>
              </main>
            </div>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
